---
abstract: 'Provides a reflexy way to talk over ZeroMQ sockets'
author:
  - 'Nicholas R. Perez <nperez@cpan.org>'
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  Reflex::Trait::Watched: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Reflexive-ZmqSocket
requires:
  Errno: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Reflex::Base: 0
  Reflex::Event: 0
  Reflex::Role::Readable: 0
  Reflex::Role::Writable: 0
  Try::Tiny: 0
  ZeroMQ::Constants: 0
  ZeroMQ::Context: 0
  ZeroMQ::Socket: 0
resources:
  repository: http://github.com/nperez/reflexive-zmq.git
version: 1.121730
